# Generated by Django 3.0.5 on 2020-05-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BBTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('primary_color_name', models.CharField(max_length=100)),
                ('primary_color_code', models.CharField(max_length=100)),
                ('secondary_color_name', models.CharField(max_length=100)),
                ('secondary_color_code', models.CharField(max_length=100)),
            ],
        ),
    ]
